name: loolwsd
version: '2.0.2'
summary: LibreOffice On-Line WebSocket Daemon
description: |
  LOOLWSD is a daemon that talks to web browser clients and provides LibreOffice
  services.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  
  loolwsd:
    command: loolwsd-start
    stop-command: killall -g loolwsd
    restart-condition: always
    daemon: simple

  flush-cache:
    command: loolwsd-cache-flush
    stop-command: killall loolwsd-service
    restart-condition: always
    daemon: simple

parts:
  poco:
    plugin: autotools
    source: https://github.com/pocoproject/poco
    source-type: git
    source-branch: develop
    configflags:
      - --no-tests
      - --no-samples
      - --no-prefix
    build-packages:
      - libpq-dev
    organize:
      lib: usr/lib
    prime:
      - usr

  loolwsd:
    plugin: loolwsd
    source: git://anongit.freedesktop.org/libreoffice/online
    source-type: git
    source-branch: distro/collabora/collabora-online-2-0
    install-via: prefix
    patches: src/loolwsd/patch
    configflags:
      - --with-lokit-path=bundled/include
      - --with-poco-includes=$SNAPCRAFT_STAGE/include
      - --prefix=$SNAPCRAFT_PART_INSTALL/usr
    organize:
      usr/etc: etc
    build-packages:
      - libpng12-dev
      - libcap-dev
      - libcppunit-dev
      - python-polib
    stage-packages:
      - libcppunit-1.13-0v5
    prime:
      - -usr/share/doc
    after: [poco]

  loolwsd-customizations:
    plugin: dump
    source: src/loolwsd
    stage:
      - -patch

  dependencies:
    plugin: repository
    stage-packages:
      - collaboraoffice5.1
      - collaboraoffice5.1-ure
      - collaboraofficebasis5.1-calc
      - collaboraofficebasis5.1-core
      - collaboraofficebasis5.1-en-us
      - collaboraofficebasis5.1-en-us-calc
      - collaboraofficebasis5.1-en-us-res
      - collaboraofficebasis5.1-graphicfilter
      - collaboraofficebasis5.1-images
      - collaboraofficebasis5.1-impress
      - collaboraofficebasis5.1-writer
      - code-brand