name: code
version: '2.0.3-1'
summary: Collabora Online Developer Edition
description: |
  Offers Office online integration with nextcloud.
  LOOLWSD (LibreOffice On-Line WebSocket Daemon) is a daemon that talks to web browser 
  clients and provides LibreOffice services.
  This snap includes also a reverse proxy to communicate other services to this one

grade: stable
confinement: strict

apps:
  loolwsd:
    command: loolwsd-start
    stop-command: killall -g loolwsd
    restart-condition: always
    daemon: simple
    plugs: [network, network-bind, nextcloud-data, system-observe, docker-support]

  flush-cache:
    command: loolwsd-cache-flush
    stop-command: killall loolwsd-service
    restart-condition: always
    daemon: simple

  reverse-proxy:
    command: run-httpd -k start -DFOREGROUND
    stop-command: run-httpd -k stop
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]

plugs:
  nextcloud-data:
    content: nextcloud-documents
    default-provider: nextcloud-nextant
    interface: content
    target: nextcloud-data

parts:
  libreoffice:
    plugin: repository
    stage-packages:
      - collaboraoffice5.1
      - collaboraoffice5.1-ure
      - collaboraofficebasis5.1-calc
      - collaboraofficebasis5.1-core
      - collaboraofficebasis5.1-en-us
      - collaboraofficebasis5.1-en-us-calc
      - collaboraofficebasis5.1-en-us-res
      - collaboraofficebasis5.1-graphicfilter
      - collaboraofficebasis5.1-images
      - collaboraofficebasis5.1-impress
      - collaboraofficebasis5.1-writer
      - code-brand
  
  system-extra-libs:
    plugin: nil
    stage-packages:
      - libx11-6
      - libc6
      - libcap2
      - libgcc1
      - libstdc++6
      - fontconfig
      - fontconfig-config
      - fonts-dejavu-core
      - fonts-freefont-ttf
      - fonts-guru
      - fonts-guru-extra
      - fonts-kacst
      - fonts-kacst-one
      - fonts-khmeros-core
      - fonts-lao
      - fonts-liberation
      - fonts-lklug-sinhala
      - fonts-lohit-guru
      - fonts-nanum
      - fonts-noto-cjk
      - fonts-opensymbol
      - fonts-sil-abyssinica
      - fonts-sil-padauk
      - fonts-stix
      - fonts-symbola
      - fonts-takao-pgothic
      - fonts-thai-tlwg
      - fonts-tibetan-machine
      - fonts-tlwg-garuda
      - fonts-tlwg-garuda-ttf
      - fonts-tlwg-kinnari
      - fonts-tlwg-kinnari-ttf       
      - fonts-tlwg-laksaman
      - fonts-tlwg-laksaman-ttf                                                                                                      
      - fonts-tlwg-loma
      - fonts-tlwg-loma-ttf
      - fonts-tlwg-mono
      - fonts-tlwg-mono-ttf
      - fonts-tlwg-norasi
      - fonts-tlwg-norasi-ttf
      - fonts-tlwg-purisa
      - fonts-tlwg-purisa-ttf
      - fonts-tlwg-sawasdee
      - fonts-tlwg-sawasdee-ttf
      - fonts-tlwg-typewriter
      - fonts-tlwg-typewriter-ttf
      - fonts-tlwg-typist
      - fonts-tlwg-typist-ttf
      - fonts-tlwg-typo
      - fonts-tlwg-typo-ttf
      - fonts-tlwg-umpush
      - fonts-tlwg-umpush-ttf
      - fonts-tlwg-waree
      - fonts-tlwg-waree-ttf
      - ghostscript
      - gsfonts
      - libfont-afm-perl
      - libfontconfig1
      - libfontembed1
      - libfontenc1
      - libxfont1
      - ttf-ancient-fonts-symbola
      - ttf-dejavu-core
      - ttf-ubuntu-font-family
      - xfonts-base
      - xfonts-encodings
      - xfonts-scalable
      - xfonts-utils
    stage:
      - -etc/fonts/fonts.conf

  systemplate:
    plugin: nil
    prepare: ./src/systemplate/loolwsd-systemplate-set.sh
    after: [libreoffice, system-extra-libs]
    stage:
      - systemplate

  poco:
    plugin: autotools
    source: https://github.com/pocoproject/poco
    source-type: git
    source-branch: master
    configflags:
      - --no-tests
      - --no-samples
      - --no-prefix
    build-packages:
      - libpq-dev
    organize:
      lib: usr/lib
    prime:
      - usr

  loolwsd:
    plugin: loolwsd
    source: git://anongit.freedesktop.org/libreoffice/online
    source-type: git
    source-branch: distro/collabora/collabora-online-2-0
    install-via: prefix
    patches: src/loolwsd/patch
    configflags:
      - --with-lokit-path=bundled/include
      - --with-poco-includes=$SNAPCRAFT_STAGE/include
      - --prefix=$SNAPCRAFT_PART_INSTALL/usr
      - --disable-ssl
    organize:
      usr/etc: etc
    build-packages:
      - libpng12-dev
      - libcap-dev
      - libcppunit-dev
      - libcups2
    prime:
      - -usr/share/doc
    after: [poco]

  loolwsd-customizations:
    plugin: dump
    source: src/loolwsd
    organize:
      conf/fonts.conf: etc/fonts/
    stage:
      - bin
      - etc
    after: [system-extra-libs]

  apache:
    plugin: apache
    source: http://apache.rediris.es/httpd/httpd-2.4.25.tar.bz2
    # The built-in Apache modules to enable
    modules:
      - headers
      - proxy
      - setenvif
      - env
      - rewrite
      - mime
      - dir
      - authz_core
      - unixd
      - alias
      - ssl
      - socache_shmcb
      - proxy_wstunnel
      - proxy_http
      - log_config
    filesets:
      exclude:
        - -man
        - -manual
        - -htdocs
        - -include
        - -build
        - -conf/httpd.conf
        - -conf/magic
        - -conf/original
        - -conf/extra
        - -bin/apachectl
        - -bin/envvars*
    stage:
      - $exclude
    prime:
      - $exclude

  apache-customizations:
    plugin: dump
    source: src/apache
